// industries.ts

export enum Industry {
  IT_Software = 'IT / Software',
  Healthcare = 'Healthcare',
  Finance = 'Finance',
  Education = 'Education',
  ECommerce = 'E-Commerce',
  Retail = 'Retail',
  Manufacturing = 'Manufacturing',
  Entertainment = 'Entertainment',
  RealEstate = 'Real Estate',
  Travel_Hospitality = 'Travel & Hospitality',
  Marketing_Advertising = 'Marketing & Advertising',
  Automotive = 'Automotive',
  Agriculture = 'Agriculture',
  Energy = 'Energy',
  Construction = 'Construction',
  Telecommunications = 'Telecommunications',
  Media = 'Media',
  Fashion_Apparel = 'Fashion & Apparel',
  Sports = 'Sports',
  Food_Beverage = 'Food & Beverage',
  NonProfit = 'Non-Profit',
  Government = 'Government',
  Other = 'Other',
};

export const industriesArray: Industry[] = [
  Industry.IT_Software,
  Industry.Healthcare,
  Industry.Finance,
  Industry.Education,
  Industry.ECommerce,
  Industry.Retail,
  Industry.Manufacturing,
  Industry.Entertainment,
  Industry.RealEstate,
  Industry.Travel_Hospitality,
  Industry.Marketing_Advertising,
  Industry.Automotive,
  Industry.Agriculture,
  Industry.Energy,
  Industry.Construction,
  Industry.Telecommunications,
  Industry.Media,
  Industry.Fashion_Apparel,
  Industry.Sports,
  Industry.Food_Beverage,
  Industry.NonProfit,
  Industry.Government,
  Industry.Other,
];
